### ISSUE TITLE
Is fluxxor compatible with react 0.13.1 and react-router 0.13.1?

### ISSUE THREAD

**Issue by ycavatars** [BinaryMuse/fluxxor#113]
hi, can I use fluxxor with react v0.13.1 and react-router v.0.13.1? In `package.json`, the devDependencies is  `"react": "^0.12.0",  "react-router": "^0.11.6",`. Thanks.

**Comment by BinaryMuse** [comment]
You should be able to use it with no problems; Fluxxor only uses React in its mixins. The `devDependencies` are there for tests and to build the examples; there's an [open Pull Request](https://github.com/BinaryMuse/fluxxor/pull/96) with the newer versions of React and React Router in the deps, but it's not merged yet due to an issue I'm having with `tcomb-form`.
