### ISSUE TITLE
Advice on chained actions

### ISSUE THREAD

**Issue by marcselman** [BinaryMuse/fluxxor#125]
I have an asynchronous action Login with a LoginSuccess and LoginFail action. They are handled inside my AuthStore. What I want is to trigger another action, (LoadFeeds) which should be handled by my FeedStore, when LoginSuccess is called.
What would be the best way to do this? I don't think I should trigger new actions from another store.

**Comment by plaxdan** [comment]
One way to handle this would be to split the login and feed loading into separate Promise-based services and then use those services from within your action creator:

```coffeescript
authService = require './services/authservice'
feedService = require './services/feedservice'

LoginActionCreator =
  
  login: (username, password) ->
    @dispatch MyActions.LOGIN_STARTED
    authService.login username, password
      .then (user) =>
        @dispatch MyActions.LOGIN_SUCCEEDED, user
        @dispatch MyActions.FEED_LOAD_STARTED
        feedService.loadFeeds user
          .then (feed) =>
            @dispatch MyActions.FEED_LOAD_SUCCEEDED, feed
          .catch (err) =>
            @dispatch MyActions.FEED_LOAD_FAILED, err
      .catch (err) =>
        @dispatch MyActions.LOGIN_FAILED, err
```

**Comment by BinaryMuse** [comment]
I agree with @plaxdan, that is a good approach. I tend to keep my action creators as semantically meaningful as possible, so I might have a `login` action creator and a `loadFeeds` action creator, because logging in doesn't semantically mean the same thing as fetching feeds, though they may be realated. Using this approach, I would probably return promises from them simply for control flow (*not* for global application data flow—that's what dispatches and stores are for):

```javascript
// action creators...

login: (username, password) {
  var loginPromise = authService.login(username, password);
  loginPromise.then((user) => {
    this.dispatch(constants.LOGIN_SUCCESS, {user});
  }, (error) => {
    this.dispatch(constants.LOGIN_FAILED, {error});
  });

  return loginPromise;
},

loadFeeds: (user) {
  var feedsPromise = feedService.loadFeeds(user);
  feedsPromise.then((feeds) => {
    this.dispatch(constants.FEEDS_LOAD_SUCCESS, {feeds});
  }, (error) => {
    this.dispatch(constants.FEEDS_LOAD_SUCCESS, {error});
  });

  return feedsPromise;
}

// where the actions are invoked...

this.getFlux().actions.login().then((user) => {
  this.getFlux().actions.loadFeeds(user);
});
```

An even better option, in my opinion, and one I've been using more and more, is to allow stores to initiate async get requests if necessary. This works really well and also makes it so you don't need to know if the request for data is local (via a cache) or not, and you don't have to call any `loadX` type action creators. I will probably update the Fluxxor site to recommend this approach; see [this Stack Overflow answer](http://stackoverflow.com/questions/26632415/where-should-ajax-request-be-made-in-flux-app/26635597#26635597) for more details on this technique.

**Comment by marcselman** [comment]
Returing promises works like a charm!
Thanks.
