### ISSUE TITLE
Only one action can be dispatched at a time

### ISSUE THREAD

**Issue by jsilvestre** [BinaryMuse/fluxxor#52]
Hello and thanks for your work here.

I've encountered a limitation of the dispatcher implementation that prevents me from having multiple actions being dispatched at the same time. While I think I do understand the reasons behind this limitation, I'd like to be sure to understand them. Could you enlighten me here please?

Anyway, I changed my code to avoid this but from what I understand from Flux and particularly in the case of various action sources, I will meet them again if I have:
- view_actions
- server_actions (xhr)
- realtime_actions (websocket)

How can I ensure that there will be one and only one action trigger at a given time since I cannot predict when all those actions are sent? I was thinking of making the dispatcher managing a queue but it's not in the official dispatcher implementation (see http://facebook.github.io/flux/docs/dispatcher.html) so I guess I'm missing something.
That's probably something I should ask the React/Flux team though, but you might help me to figure this out.

**Comment by droberts84** [comment]
@jawb Think of the events more as business events that different components can choose how to respond to.. not specific instructions of how to change the view.  In your case you should have a single event defined for whatever is triggering this action.  Your stores and views can react to this event by opening the modal and removing the data (Remember that multiple stores can be listening to the same event)

**Comment by skatou** [comment]
According to @BinaryMuse and @jsilvestre, two constraints we need to obey to prevent two actions dispatched at the same time,
1. don't dispatch new action within an action handler;
2. dispatching loop should be synchronous.

I totally agree with #1, but constraint #2 is so strong that prevent me from applying some design decisions.

Before I read this issue I planned to have my Store doing two optional tasks on receiving an action,
1. making XHR calls;
2. persisting store data.

Knowing that dispatching loop should be synchronous, I decided to move XHR calls out of action handler, only after the XHR calls are finished I create an action and make the dispatch call, this is fine since making XHR calls doesn't require much knowledge about the inner structure of Store.

But I am stuck in the data persistent part. I am working with react-native and want to persist data with AsyncStore or through my exposed sqlite module, the persistent works in async way. I can ignore the async callbacks but it leads to inconsistent on failure.

What should be the best practice?

**Comment by skatou** [comment]
OK I understand, per @BinaryMuse's comment, It's fine to dispatch a new action in async callback, so in my case I can finish the task with two actions: one for triggering data persistent, the other for triggering UI update on data persistent result.
