### ISSUE TITLE
StoreWatchMixin can add a listener to the same store multiple time

### ISSUE THREAD

**Issue by patrick-fls** [BinaryMuse/fluxxor#94]
Maybe it's terrible design on my part, but I ran in the issue where if I use the mixin to watch the same store in different components, the "change" event is triggered as many time as the store is registered in the mixin, thus calling the setState many time - forcing multiple re-renders.

I fixed the issue by doing a quick hack:

````javascript
var _each = require("lodash-node/modern/collections/forEach");

+++ var alreadyWatching =  [];

var StoreWatchMixin = function() {
  var storeNames = Array.prototype.slice.call(arguments);
  return {
    componentDidMount: function() {
      var flux = this.props.flux || this.context.flux;
      _each(storeNames, function(store) {
+++        if(alreadyWatching.indexOf(store) < 0) {
          flux.store(store).on("change", this._setStateFromFlux);
+++          alreadyWatching.push(store);
+++        }
      }, this);
    },
[...]
````

Am I crazy?

**Comment by BinaryMuse** [comment]
That doesn't sound like the behavior I'd expect — do you have an example that shows this problem in action that I could take a look at?

**Comment by patrick-fls** [comment]
Unfortunately it's on NDA code :(
Reading at the doc of EventEmitter: http://nodejs.org/api/events.html#events_emitter_on_event_listener

It seems like we can chain the "On". Isn't what the mixin doing in effect?

**Comment by BinaryMuse** [comment]
When you use `StoreWatchMixin` in different components, the updates are scoped to that component—that is to say, change events for a watched store are handled once *per component*.

Consider the following quick-and-dirty example, which you can find running on JSFiddle at http://jsfiddle.net/BinaryMuse/1y1xc7yt/

```javascript
var StoreA = fluxxor.createStore({
  actions: {
    "ADD_ONE": "handleAddOne"
  },
  
  initialize: function() {
    this.value = 0;
  },
  
  handleAddOne: function() {
    this.value++;
    this.emit("change");
  }
});

var StoreB = fluxxor.createStore({
  actions: {
    "MINUS_ONE": "handleMinusOne"
  },
  
  initialize: function() {
    this.value = 0;
  },
  
  handleMinusOne: function() {
    this.value--;
    this.emit("change");
  }
});

var flux = new fluxxor.Flux({store1: new StoreA(), store2: new StoreB()});

var App = React.createClass({
  mixins: [fluxxor.FluxMixin(React)],

  render: function() {
    return <div>
      <ComponentA />
      <ComponentB />
      <hr />
      <div>
        <button onClick={this.handlePlusClick}>Add One</button>
        <button onClick={this.handleMinusClick}>Minus One</button>
        <button onClick={this.handleBothClick}>Both at Once</button>
      </div>
    </div>;
  },
  
  handlePlusClick: function() {
    flux.dispatcher.dispatch({type: "ADD_ONE"});
  },
  
  handleMinusClick: function() {
    flux.dispatcher.dispatch({type: "MINUS_ONE"});
  },
  
  handleBothClick: function() {
    this.handlePlusClick();
    this.handleMinusClick();
  }
});

var ComponentA = React.createClass({
  mixins: [
    fluxxor.FluxMixin(React),
    fluxxor.StoreWatchMixin("store1", "store2")
  ],
  
  count: 0,
  
  getStateFromFlux: function() {
    this.count++;
    return {};
  },
  
  render: function() {
    console.log("ComponentA render");
    return <div>
      Component A - getStateFromFlux called {this.count} times
    </div>;
  }
});

var ComponentB = React.createClass({
  mixins: [
    fluxxor.FluxMixin(React),
    fluxxor.StoreWatchMixin("store2")
  ],
  
  count: 0,
  
  getStateFromFlux: function() {
    this.count++;
    return {};
  },
  
  render: function() {
    console.log("ComponentB render");
    return <div>
      Component B - getStateFromFlux called {this.count} times
    </div>;
  },
});
 
React.render(<App flux={flux} />, document.body);
```

The top component (`ComponentA`) listens to both stores; the bottom component (`ComponentB`) only listens to the second store (the one that updates via the "minus" event). Each time you click the "plus" button, the top component gets updated once. Each time you click the "minus" button, both the top and bottom components get updated, but each still only once.

Notice if you click the third button, which dispatches *both* actions, that the top component is updated *twice*, while the bottom one is updated only once. This is because the top component is listening to both stores, and both stores emitted a change event, thus each event was handled separately. However, if you look for the `console.log` messages in your console, you'll see that this behavior is still only triggering one re-render, because React batches state updates together. As long as `getStateFromFlux` is fast, change events from multiple stores shouldn't be an issue.

I don't believe there is a bug here, but if you can demonstrate the problem to me (e.g. via a JSFiddle example or some other reproducible test case) please let me know.

**Comment by patrick-fls** [comment]
I can't thank you enough for taking the time to write this lengthy explanation. It helped me debug something nasty in my code. 

In the hope It helps somebody one day:

I had a factory (or so I thought) creating a base store with a couple of things I want to use in every store. Little did I realize that requirejs creates a singleton no matter what.

My factory was, in effect, just a single ton and all my stores added their own functions to it  ( with lodash merge) including the actions....and the listeners. That's why events where triggered multiple times: each of my store had a listener for each available action. 

I'm sorry I made you waste your time. Thanks again!

**Comment by BinaryMuse** [comment]
Great! I'm glad you were able to track down the problem. Thanks for sharing the solution with us!
