### ISSUE TITLE
Fluxxor does not work with the v 3.x update to lodash

### ISSUE THREAD

**Issue by marcus** [BinaryMuse/fluxxor#98]
The paths to require specific portions of lodash have gone from using plurals (objects) to singular (object). I would suggest just:
```_ = require('lodash_node');```
If you're on board with that, I can change it and submit a PR.

**Comment by BinaryMuse** [comment]
Hey, @marcus,

Is this causing a problem/bug? Since the version of lodash-node is specified as `^2.4.1` in Fluxxor's `package.json`, it should not be installing v3.x. That said, I'm fine with upgrading to the latest version of lodash-node; I heard there were some nice performance improvements.

However, I'm not keen on requiring the entire lodash-node library, as it contributes considerably to the final bundle's file size—see f1d516260c7ddd6e6a5a91a2833481c645a98777, the commit that brought the file size down by approximately 40% in v1.1.1.

**Comment by marcus** [comment]
Yeah, it shouldn't cause a problem for most people. In any case, I created a PR (https://github.com/BinaryMuse/fluxxor/pull/99) updating to lodash 3.0.1 while keeping the same way of referencing individual lodash methods that is currently used.

**Comment by BinaryMuse** [comment]
Closed by #99 / 5c56be34dc960e550f8b5f83a3b18d611779fd76
